object Versions {
    const val kotlin = "1.5.21"
    const val appCompat = "1.3.1"
    const val material = "1.4.0"
    const val jUnit = "4.13.2"
    const val ktxCore = "1.6.0"
    const val navVersion = "2.3.5"
    const val multidex = "2.0.1"
    const val okhttp: String = "4.7.2"
    const val coroutines: String = "1.3.9"
    const val daggerHiltAndroid = "2.38.1"
    const val kotlinVersion: String = "1.4.31"
    const val testExt: String = "1.1.1"
    const val lifecycleVersion = "2.4.0-alpha03"
    const val truth: String = "1.0.1"
    const val robolectric: String = "4.3.1"
    const val androidXTestCore: String = "1.4.0"
    const val javaxInject: String = "1"
    const val hiltViewModel: String = "1.0.0-alpha02"
    const val retrofitVersion: String = "2.9.0"
    const val runner: String = "1.2.0"
    const val mockWebServer: String = "4.7.2"
}